export const TIPS = [
  { tag: 'Input', title: 'Cut filler and pleasantries', body: '"I would like you to please write..." is just "Write...". Greetings, thanks and hedge words cost tokens on every call and change nothing. The optimizer above removes them for you.', example: ['Could you please, in order to save time, write a very very good summary?', 'Write a very good summary.'] },
  { tag: 'Input', title: 'Stable text first, changing text last', body: 'Providers cache repeated prompt prefixes and bill cached input at roughly 10% of the normal price (OpenAI and Anthropic ~90% off, DeepSeek automatic). Put system prompt, rules and reference docs first; put the new question at the end.' },
  { tag: 'Input', title: 'Send only the context that matters', body: 'Paste the relevant function, not the whole repo; the relevant paragraph, not the whole PDF. Strip comments, boilerplate and repeated headers. Every token you send is re-read on every turn.' },
  { tag: 'Input', title: 'Use compact data formats', body: 'Repeated JSON keys are expensive. For lists of records, CSV or short keys carry the same data in noticeably fewer tokens.' },
  { tag: 'Input', title: 'Two good examples beat six', body: 'Few-shot examples are re-sent every call. One or two sharp, varied examples usually teach the format as well as a long list.' },
  { tag: 'Output', title: 'Ask for the shape of the answer', body: 'Output tokens cost 4-6x more than input across these providers. Say "code only", "max 5 bullets", "JSON only, no explanation" - and set max_tokens as a safety cap.', example: ['Explain how to reverse a string.', 'Reverse a string in Python. Code only, no explanation.'] },
  { tag: 'Output', title: 'Match reasoning effort to the task', body: 'Reasoning tokens are billed as output. Use low effort (or a thinking budget) for simple tasks and save high effort for genuinely hard ones. "Think step by step" is usually redundant on reasoning models.' },
  { tag: 'Conversation', title: 'One clear prompt beats five vague ones', body: 'Every follow-up re-sends the whole conversation. A specific first prompt (language, framework, requirements, output format) usually finishes in fewer turns, which is cheaper even though the first prompt is longer.' },
  { tag: 'Conversation', title: 'Restart long chats with a summary', body: 'After 20+ turns you are paying to re-read a huge history each time. Ask for a short summary of decisions so far and start a fresh conversation with it.' },
  { tag: 'Money', title: 'Route by difficulty', body: 'Use the cheap tier (GPT-5.6 Luna, Claude Haiku 4.5, Gemini Flash-Lite, DeepSeek Flash) for classification, extraction and drafts. Escalate to Sol / Opus / Pro only when the cheap model fails.' },
  { tag: 'Money', title: 'Batch anything that can wait', body: 'Anthropic and Google both offer a 50% discount on batch jobs. DeepSeek charges half price outside its weekday peak windows - schedule bulk work off-peak.' },
  { tag: 'Money', title: 'Watch the long-context cliffs', body: 'OpenAI GPT-5.6 bills higher rates for the whole request above ~272K input tokens, and Gemini 3.1 Pro raises its price above 200K. Trim context before you cross them.' },
  { tag: 'Money', title: 'Compare tokenizers, not just prices', body: 'The same text becomes different token counts on different models. Claude 4.7+ tokenizers use about 30% more tokens than older Claude models, so a cheaper rate card can still cost more. Count with the provider\'s own counter.' }
];

export const FAQS = [
  { q: 'What exactly is a token?', a: 'A chunk of text the model reads at once - a word, part of a word, or punctuation. In English, roughly 100 tokens is about 75 words. Code, numbers and non-English text usually use more tokens per word.' },
  { q: 'Is the prompt token count exact?', a: 'For OpenAI models: yes, it is computed locally with the real o200k_base tokenizer. For Claude and Gemini: it is an estimate (the OpenAI count times a ratio) unless you add ANTHROPIC_API_KEY / GEMINI_API_KEY to .env - then the selected agent is counted with the provider\'s own free token-counting endpoint and marked exact. DeepSeek is always estimated here.' },
  { q: 'Can the output tokens be predicted exactly?', a: 'No - not by this app, not by any tool. Output is generated one token at a time and depends on the model, sampling, hidden reasoning tokens and (for agents) how many tool calls and retries happen. You only learn the true number after the run, from the usage field in the API response. Everything before that is a forecast, which is why the app shows a range.' },
  { q: 'Why is the full-task number a range?', a: 'Real usage depends on how many files the model reads, how many times it retries, how much it reasons, and how big tool outputs are. A range is honest; a single number would be false precision. The forecast is Low confidence unless the optional AI planner is enabled.' },
  { q: 'Why does the forecast for "make a calculator app" look small?', a: 'The built-in formula is a rough heuristic. Real agent runs are dominated by input tokens because every step re-sends the growing conversation, so a run can be many times larger than one reply. Run the task once on a cheap model, read the real usage numbers, and enter them in "Have real numbers?" to get true costs on every agent.' },
  { q: 'Why do prices differ so much between agents?', a: 'Providers price by capability tier. Output usually costs 4-6x more than input. Cached input is about 10x cheaper than fresh input. Check the notes in the provider card: Gemini 3.8 Flash is on introductory pricing until 2026-12-31 and DeepSeek halves its price outside weekday peak hours.' },
  { q: 'Does my prompt leave my computer?', a: 'Not by default. Counting and rule-based optimization run on your own local server. Your text is sent to a third party only if you add keys: OPENAI_API_KEY (AI planner / AI rewrite), ANTHROPIC_API_KEY or GEMINI_API_KEY (exact counts for those agents).' },
  { q: 'Will the optimizer change what my prompt means?', a: 'It only removes wording that does not carry instructions (greetings, "please", filler adverbs, wordy phrases) and never edits fenced code blocks. It keeps words like "just" and "only" because they can change meaning. Always skim the result before using it.' },
  { q: 'A shorter prompt is not always cheaper, right?', a: 'Correct. If a very short prompt is vague, you pay for extra turns to fix it. The optimizer shows "prompt health" tips for that: add the language, the output format and the constraints even if it makes the prompt a little longer.' }
];
